add: ctwm (attempt 2)
terrapkg/packages pull request #1400
Opened 2024-06-27 21:54 UTC by nothingneko

closes #1030

2024-06-28 13:45 UTC, madonuko requested changes

2024-06-28 13:45 UTC, madonuko commented on anda/desktops/ctwm/anda.hcl
> +  project pkg {
indent

2024-06-28 13:45 UTC, madonuko commented on anda/desktops/ctwm/ctwm.spec
> +Version: 4.1.0
```ts
rpm.version(find("<p>Current release: ([\\d.]+)</p>", get("https://www.ctwm.org/download.html"), 1));
```

2024-06-28 13:45 UTC, madonuko commented on anda/desktops/ctwm/ctwm.spec
> +Release: 1
```suggestion
Release: 1%?dist
```

2024-06-28 13:45 UTC, madonuko commented on anda/desktops/ctwm/ctwm.spec
> +%doc README.md CHANGES.md
```suggestion
```

2024-12-18 00:32 UTC, nothingneko commented on anda/desktops/ctwm/ctwm.spec
> +* Thu Jun 27 2024 Jaiden Riordan <jade@fyralabs.com> - 4.1.0
@Owen-sz  take some credit

2024-12-18 02:59 UTC, Owen-sz commented on anda/desktops/ctwm/ctwm.spec
> +* Thu Jun 27 2024 Jaiden Riordan <jade@fyralabs.com> - 4.1.0
Ok lol

2024-12-18 03:25 UTC, Owen-sz commented
Mado please verify the rhai/sources are good (referring to thishttps://github.com/terrapkg/packages/pull/1039/files#r1550841803)

2024-12-18 05:35 UTC, madonuko approved these changes

2024-12-18 17:41 UTC, merged

2024-12-18 17:42 UTC, raboneko commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2671">](https://github.com/terrapkg/packages/pull/2671)|
|✅|f40|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2672">](https://github.com/terrapkg/packages/pull/2672)|
|✅|f41|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2673">](https://github.com/terrapkg/packages/pull/2673)|
|✅|el10|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2674">](https://github.com/terrapkg/packages/pull/2674)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/12398388727) for details

<!--- Backport version: 9.3.0 -->