fix: Do not strip binaries in submarine
terrapkg/packages pull request #1428
Opened 2024-07-05 15:51 UTC by korewaChino

2024-07-05 22:34 UTC, lleyton requested changes

2024-07-05 22:34 UTC, lleyton commented on anda/system/submarine/submarine.spec
> +%global __os_install_post %{nil}
I'm unsure where you got this from, this should work:
```suggestion
%define __strip /bin/true
```

2024-07-06 14:21 UTC, korewaChino commented
rawhide packages are broken again

2024-07-09 01:09 UTC, korewaChino commented
upstream packages are broken, merge is stil possible

2024-07-09 01:35 UTC, korewaChino commented
Tested on a local build (f40, terra mock chroot), seems to build

2024-07-09 01:36 UTC, nothingneko approved these changes, later dismissed

2024-07-09 03:14 UTC, korewaChino commented
I have attempted to build [590fd9a](https://github.com/terrapkg/packages/pull/1428/commits/590fd9a8bb9dcd25129a9ed0b7044daf7dbf0147), works

2024-07-09 03:41 UTC, korewaChino commented
rebased to 40 to work around upstream

2024-07-09 03:47 UTC, lleyton approved these changes

2024-07-09 03:47 UTC, merged

2024-07-09 03:48 UTC, raboneko commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/1443">](https://github.com/terrapkg/packages/pull/1443)|
|✅|frawhide|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/1444">](https://github.com/terrapkg/packages/pull/1444)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/9850664367) for details

<!--- Backport version: 9.3.0 -->