feat(ci): add support for terra extra
terrapkg/packages pull request #2036
Opened 2024-08-31 09:56 UTC by madonuko

2024-08-31 21:20 UTC, lleyton requested changes

2024-08-31 21:20 UTC, lleyton commented on .github/workflows/autobuild.yml
> -            terra${{ matrix.version }} anda-build/rpm/rpms/*
for source packages too?

2024-09-02 09:37 UTC, lleyton approved these changes

2024-09-02 09:38 UTC, merged

2024-09-02 09:38 UTC, raboneko commented
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|f41|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 2036
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10664689685) for details

<!--- Backport version: 9.3.0 -->