Add stardust-server
terrapkg/packages pull request #2048
Opened 2024-09-07 18:34 UTC by Owen-sz

2024-09-09 06:40 UTC, madonuko requested changes

2024-09-09 06:40 UTC, madonuko commented on anda/stardust/black-hole/update.rhai
> +  }
```suggestion
  }
}
```

Indentation?

2024-09-09 06:40 UTC, madonuko commented on anda/stardust/black-hole/stardust-black-hole.spec
> +Requires:       libgcc glibc glibm
```suggestion
```
Automatically added by rpmbuild

2024-09-09 06:40 UTC, madonuko commented on anda/stardust/black-hole/stardust-black-hole.spec
> +Source0:        https://github.com/StardustXR/black-hole/archive/%commit/black-hole-%commit.tar.gz
```suggestion
Source0:        %url/archive/%commit/black-hole-%commit.tar.gz
```
don't repeat yourself

2024-09-09 06:40 UTC, madonuko commented on anda/stardust/black-hole/stardust-black-hole.spec
> +%cargo_build
```suggestion
```
Don't build twice

2024-09-09 06:41 UTC, madonuko commented
Also you don't need the if statement in the rhai script

2024-09-10 11:05 UTC, madonuko requested changes

2024-09-10 11:05 UTC, madonuko commented on anda/stardust/black-hole/update.rhai
> +  }
mismatch

2024-09-10 11:05 UTC, madonuko commented on anda/stardust/black-hole/update.rhai
> +}
and you don't need the if statement

2024-09-10 18:52 UTC, Owen-sz commented on anda/stardust/black-hole/update.rhai
> +  }
Oops

2024-09-10 18:57 UTC, Owen-sz commented on anda/stardust/black-hole/update.rhai
> +  }
Will fix tonight

2024-09-11 03:59 UTC, madonuko commented on anda/stardust/black-hole/update.rhai
> +rpm.global("commit", gh_commit("StardustXR/server"));
```suggestion
rpm.global("commit", gh_commit("StardustXR/server"));
if rpm.changed() {
  rpm.release();
  rpm.global("commit_date", date());
}
```

2024-09-11 08:42 UTC, madonuko commented on anda/stardust/server/stardust-server.spec
> +Source0:        %url/archive/refs/tags/0.44.1.tar.gz
```suggestion
Source0:        %url/archive/refs/tags/%version.tar.gz
```

2024-09-13 16:53 UTC, madonuko approved these changes, later dismissed

2024-09-13 17:21 UTC, madonuko approved these changes, later dismissed

2024-09-16 13:27 UTC, madonuko submitted a review, later dismissed

2024-10-23 04:29 UTC, madonuko submitted a review, later dismissed

2024-10-23 04:29 UTC, madonuko commented
Next time please mark this as ready for review (un-draft this)

2024-10-23 04:36 UTC, Owen-sz commented
> Next time please mark this as ready for review (un-draft this)

Was waiting for the RPM to be tested before I did that, it used to build before but still didn't preform as expected.

2024-10-23 14:50 UTC, nothingneko approved these changes

2024-10-23 14:50 UTC, merged

2024-10-23 14:51 UTC, raboneko commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2305">](https://github.com/terrapkg/packages/pull/2305)|
|✅|f40|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2306">](https://github.com/terrapkg/packages/pull/2306)|
|✅|f41|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2307">](https://github.com/terrapkg/packages/pull/2307)|
|✅|el10|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2308">](https://github.com/terrapkg/packages/pull/2308)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/11482481965) for details

<!--- Backport version: 9.3.0 -->