Add stardust-flatland
terrapkg/packages pull request #2049
Opened 2024-09-07 20:44 UTC by Owen-sz

2024-09-09 06:42 UTC, madonuko requested changes

2024-09-09 06:42 UTC, madonuko commented on anda/stardust/flatland/stardust-flatland.spec
> +%cargo_build
```suggestion
```
Don't build twice

2024-09-09 06:42 UTC, madonuko commented on anda/stardust/flatland/stardust-flatland.spec
> +Source0:        https://github.com/StardustXR/flatland/archive/%commit/flatland-%commit.tar.gz
```suggestion
Source0:        %url/archive/%commit/flatland-%commit.tar.gz
```

2024-09-09 06:42 UTC, madonuko commented on anda/stardust/flatland/update.rhai
> +if filters.contains("nightly") {
You don't need this if statement.

2024-09-09 06:42 UTC, madonuko commented on anda/stardust/flatland/stardust-flatland.spec
> +Requires:       libgcc glibc
You probably don't need this

2024-09-09 06:42 UTC, madonuko commented on anda/stardust/flatland/stardust-flatland.spec
> +Flatland for StardustXR.
```suggestion
%summary
```

2024-09-09 06:42 UTC, madonuko commented on anda/stardust/flatland/stardust-flatland.spec
> +Flatland for StardustXR.
Also, `Summary:` usually doesn't end with `.`s

2024-09-10 11:15 UTC, madonuko requested changes

2024-09-10 11:15 UTC, madonuko commented on anda/stardust/flatland/stardust-flatland.spec
> +Provides:       flatland
Packager

2024-09-10 11:15 UTC, madonuko commented on anda/stardust/flatland/update.rhai
> +if filters.contains("nightly") {
remove the `if ...` and the brackets

2024-09-11 04:02 UTC, madonuko requested changes

2024-09-11 04:02 UTC, madonuko commented on anda/stardust/flatland/anda.hcl
> +labels {
indentation

2024-09-11 04:02 UTC, madonuko commented on anda/stardust/flatland/update.rhai
> +rpm.global("commit", gh_commit("StardustXR/flatland"));
```suggestion
rpm.global("commit", gh_commit("StardustXR/flatland"));
if rpm.changed() {
  rpm.release();
  rpm.global("commit_date", date());
}
```

2024-09-11 11:04 UTC, madonuko approved these changes, later dismissed

2024-09-11 14:37 UTC, korewaChino submitted a review, later dismissed
it do build

2024-09-13 16:12 UTC, madonuko approved these changes, later dismissed

2024-09-13 17:29 UTC, madonuko approved these changes, later dismissed

2024-09-16 13:27 UTC, madonuko approved these changes

2024-09-19 14:28 UTC, merged

2024-09-19 14:29 UTC, raboneko commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2095">](https://github.com/terrapkg/packages/pull/2095)|
|✅|f40|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2096">](https://github.com/terrapkg/packages/pull/2096)|
|✅|f41|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2097">](https://github.com/terrapkg/packages/pull/2097)|
|✅|el9|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2098">](https://github.com/terrapkg/packages/pull/2098)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10943072340) for details

<!--- Backport version: 9.3.0 -->