Add stardust-armillary
terrapkg/packages pull request #2050
Opened 2024-09-07 21:04 UTC by Owen-sz

2024-09-09 06:43 UTC, madonuko requested changes
also make yourself the `Packager:` in all 3 packages

2024-09-09 06:43 UTC, madonuko commented on anda/stardust/armillary/stardust-armillary.spec
> +Source0:        https://github.com/StardustXR/armillary/archive/%commit/armillary-%commit.tar.gz
again, don't repeat yourself

2024-09-09 06:43 UTC, madonuko commented on anda/stardust/armillary/stardust-armillary.spec
> +Requires:       libgcc glibc
probably don't need this too

2024-09-09 06:43 UTC, madonuko commented on anda/stardust/armillary/stardust-armillary.spec
> +%cargo_build
remove this

2024-09-09 06:43 UTC, madonuko commented on anda/stardust/armillary/update.rhai
> +if filters.contains("nightly") {
don't need this

2024-09-10 11:04 UTC, madonuko requested changes

2024-09-10 11:04 UTC, madonuko commented on anda/stardust/armillary/stardust-armillary.spec
> +Requires:       libgcc glibc
?

2024-09-10 11:04 UTC, madonuko commented on anda/stardust/armillary/update.rhai
> +if filters.contains("nightly") {
?

2024-09-11 11:04 UTC, madonuko approved these changes, later dismissed

2024-09-13 16:12 UTC, madonuko approved these changes

2024-09-19 14:27 UTC, merged

2024-09-19 14:27 UTC, raboneko commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2087">](https://github.com/terrapkg/packages/pull/2087)|
|✅|f40|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2088">](https://github.com/terrapkg/packages/pull/2088)|
|✅|f41|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2089">](https://github.com/terrapkg/packages/pull/2089)|
|✅|el9|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2090">](https://github.com/terrapkg/packages/pull/2090)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10943048566) for details

<!--- Backport version: 9.3.0 -->