Add stardust-comet
terrapkg/packages pull request #2051
Opened 2024-09-07 21:33 UTC by Owen-sz

2024-09-09 06:45 UTC, madonuko reviewed
also you accidentally assigned me and lea instead of asking for a review

2024-09-09 06:45 UTC, madonuko commented on anda/stardust/comet/stardust-comet.spec
> +%cargo_build
don't need this

2024-09-09 06:45 UTC, madonuko commented on anda/stardust/comet/stardust-comet.spec
> +Requires:       libgcc glibc
don't need this

2024-09-09 06:45 UTC, madonuko commented on anda/stardust/comet/stardust-comet.spec
> +Source0:        https://github.com/StardustXR/comet/archive/%commit/comet-%commit.tar.gz
dry

2024-09-09 06:45 UTC, madonuko commented on anda/stardust/comet/update.rhai
> +if filters.contains("nightly") {
don't need this

2024-09-09 06:45 UTC, madonuko commented on anda/stardust/comet/stardust-comet.spec
> +Provides:       comet
add `Packager:`

2024-09-09 06:45 UTC, madonuko commented on anda/stardust/comet/stardust-comet.spec
> +Annotate things in Stardust
full stop here, remove full stop from Summary

2024-09-09 19:31 UTC, Owen-sz commented on anda/stardust/comet/stardust-comet.spec
> +Provides:       comet
Done, is that set correctly?

2024-09-10 11:18 UTC, madonuko requested changes

2024-09-10 11:18 UTC, madonuko commented on anda/stardust/comet/stardust-comet.spec
> +Requires:       libgcc glibc
?

2024-09-10 11:18 UTC, madonuko commented on anda/stardust/comet/stardust-comet.spec
> +Provides:       comet
lgtm

2024-09-10 11:18 UTC, madonuko commented on anda/stardust/comet/update.rhai
> +if filters.contains("nightly") {
remove the if statement

2024-09-11 11:05 UTC, madonuko approved these changes, later dismissed

2024-09-13 16:13 UTC, madonuko submitted a review, later dismissed

2024-09-13 17:30 UTC, madonuko approved these changes

2024-09-19 14:28 UTC, merged

2024-09-19 14:29 UTC, raboneko commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2099">](https://github.com/terrapkg/packages/pull/2099)|
|✅|f40|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2100">](https://github.com/terrapkg/packages/pull/2100)|
|✅|f41|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2101">](https://github.com/terrapkg/packages/pull/2101)|
|✅|el9|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2102">](https://github.com/terrapkg/packages/pull/2102)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10943076375) for details

<!--- Backport version: 9.3.0 -->