Add stardust-black-hole
terrapkg/packages pull request #2052
Opened 2024-09-08 06:02 UTC by Owen-sz

2024-09-09 06:47 UTC, madonuko reviewed
add `Packager`

also you assigned me instead of request review

2024-09-09 06:47 UTC, madonuko commented on anda/stardust/black-hole/stardust-black-hole.spec
> +Source0:        https://github.com/StardustXR/black-hole/archive/%commit/black-hole-%commit.tar.gz
dry

2024-09-09 06:47 UTC, madonuko commented on anda/stardust/black-hole/stardust-black-hole.spec
> +Spatial storage for stardust xr
dry and full stop

2024-09-09 06:47 UTC, madonuko commented on anda/stardust/black-hole/stardust-black-hole.spec
> +Requires:       libgcc glibc
don't need this

2024-09-09 06:47 UTC, madonuko commented on anda/stardust/black-hole/stardust-black-hole.spec
> +%cargo_build
don't need this

2024-09-09 06:47 UTC, madonuko commented on anda/stardust/black-hole/update.rhai
> +if filters.contains("nightly") {
don't need this

2024-09-10 11:17 UTC, madonuko requested changes

2024-09-10 11:17 UTC, madonuko commented on anda/stardust/black-hole/stardust-black-hole.spec
> +Requires:       libgcc glibc
?

2024-09-10 11:17 UTC, madonuko commented on anda/stardust/black-hole/update.rhai
> +if filters.contains("nightly") {
?

2024-09-10 18:48 UTC, Owen-sz commented on anda/stardust/black-hole/stardust-black-hole.spec
> +Requires:       libgcc glibc
Removing now

2024-09-11 04:40 UTC, Owen-sz commented on anda/stardust/black-hole/stardust-black-hole.spec
> +Spatial storage for stardust xr
What do you mean?

2024-09-11 10:54 UTC, madonuko submitted a review, later dismissed

2024-09-13 16:13 UTC, madonuko submitted a review, later dismissed

2024-09-13 17:29 UTC, madonuko submitted a review, later dismissed

2024-09-16 13:27 UTC, madonuko approved these changes

2024-09-19 14:28 UTC, merged

2024-09-19 14:28 UTC, raboneko commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2091">](https://github.com/terrapkg/packages/pull/2091)|
|✅|f40|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2092">](https://github.com/terrapkg/packages/pull/2092)|
|✅|f41|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2093">](https://github.com/terrapkg/packages/pull/2093)|
|✅|el9|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2094">](https://github.com/terrapkg/packages/pull/2094)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10943068916) for details

<!--- Backport version: 9.3.0 -->