Add stardust protostar
terrapkg/packages pull request #2056
Opened 2024-09-10 01:48 UTC by Owen-sz

WIP

2024-09-10 01:49 UTC, Owen-sz commented
I don't know why this is failing, could be due to the multiple results after it compiles..?

2024-09-10 11:10 UTC, madonuko requested changes

2024-09-10 11:10 UTC, madonuko commented on anda/stardust/non-spatial-input/stardust-non-spatial-input.spec
> +Requires:       libgcc glibc
don't need this

2024-09-10 11:10 UTC, madonuko commented on anda/stardust/non-spatial-input/stardust-non-spatial-input.spec
> +%cargo_install
here you are building all the projects in that repository

either `cd` into each of them to run `%cargo_install` (+ remove %cargo_build), or manually run the `install -Dpm755` command

2024-09-10 11:10 UTC, madonuko commented on anda/stardust/non-spatial-input/update.rhai
> +if filters.contains("nightly") {
don't need this

2024-09-10 11:10 UTC, madonuko commented on anda/stardust/non-spatial-input/stardust-non-spatial-input.spec
> +%_bindir/non-spatial-input
no such project/file

2024-09-10 11:10 UTC, madonuko commented on anda/stardust/non-spatial-input/stardust-non-spatial-input.spec
> +%global debug_package %{nil}
bad idea for a rust package, remove this line

2024-09-10 11:10 UTC, madonuko commented on anda/stardust/protostar/update.rhai
> +if filters.contains("nightly") {
again don't need this

2024-09-10 11:10 UTC, madonuko commented on anda/stardust/protostar/stardust-protostar.spec
> +%cargo_install
```suggestion
cd protostar
%cargo_install
```
probably this? I assume that's what you want to do?

2024-09-10 11:10 UTC, madonuko commented on anda/stardust/protostar/stardust-protostar.spec
> +Requires:       libgcc glibc
don't need this

2024-09-13 17:25 UTC, madonuko submitted a review, later dismissed

2024-09-16 13:27 UTC, madonuko approved these changes

2024-09-16 19:23 UTC, merged

2024-09-16 19:24 UTC, raboneko commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|f39|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2075">](https://github.com/terrapkg/packages/pull/2075)|
|✅|f40|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2076">](https://github.com/terrapkg/packages/pull/2076)|
|✅|f41|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2077">](https://github.com/terrapkg/packages/pull/2077)|
|✅|el9|[<img src="https://img.shields.io/github/pulls/detail/state/terrapkg/packages/2078">](https://github.com/terrapkg/packages/pull/2078)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/terrapkg/packages/actions/runs/10890643048) for details

<!--- Backport version: 9.3.0 -->