fix: armcord
terrapkg/packages pull request #636
Opened 2023-07-19 06:12 UTC by windowsboy111

2023-07-19 11:20 UTC, lexisother requested changes

2023-07-19 11:20 UTC, lexisother commented on anda/apps/armcord/armcord.spec
> -BuildRequires:	nodejs-npm
Formatting.

2023-07-25 08:30 UTC, lexisother commented on anda/apps/armcord/armcord.spec
> +npx pnpm@7 install --no-frozen-lockfile
why are we installing deps twice?

2023-07-25 08:39 UTC, windowsboy111 commented on anda/apps/armcord/armcord.spec
> +npx pnpm@7 install --no-frozen-lockfile
should be fixed

2023-07-26 14:15 UTC, lexisother approved these changes

2023-07-26 14:15 UTC, merged