add: uutils-coreutils
terrapkg/packages pull request #744
Opened 2023-10-19 06:11 UTC by madonuko

2023-10-20 14:11 UTC, korewaChino approved these changes

2023-10-20 14:12 UTC, korewaChino approved these changes, later dismissed

2023-10-20 16:44 UTC, nothingneko submitted a review, later dismissed
LGTM!!

2023-10-20 18:53 UTC, lleyton requested changes

2023-10-20 18:53 UTC, lleyton commented on anda/tools/uutils-coreutils/uutils-coreutils.spec
> +Requires:		glibc gcc-devel
gcc-devel is not a real package, what are you actually trying to pull in?

2023-10-21 03:11 UTC, lleyton requested changes
good and bad news

good: it installs now
bad: I'm not sure why we have the uu- prefix on the binaries (and don't symlink)

2023-10-23 05:53 UTC, korewaChino approved these changes, later dismissed

2023-10-29 09:05 UTC, korewaChino commented
Many packages require coreutils itself. We need to somehow make the dep solver know that uutils can replace them all.

2023-11-01 01:38 UTC, lleyton submitted a review, later dismissed

2023-11-01 01:54 UTC, lleyton approved these changes

2023-11-01 01:55 UTC, merged