add: arrpc
terrapkg/packages pull request #920
Opened 2024-02-06 09:39 UTC by madonuko

2024-02-08 21:10 UTC, lleyton requested changes
systemd macros?

2024-02-09 10:15 UTC, korewaChino approved these changes, later dismissed
ok lgtm

2024-02-09 23:21 UTC, lleyton commented
> nothing provides gcc-libs needed by arrpc-3.3.0-1.fc39.x86_64 from @commandline

2024-02-11 03:48 UTC, lleyton approved these changes

2024-02-11 03:48 UTC, lleyton commented on anda/misc/arrpc/arrpc.spec
> +
if the service can be restarted, you should have a postun with systemd_user_postun_with_restart

2024-02-11 03:50 UTC, lleyton requested changes
sorry, don't know why I did a approve

2024-02-12 04:34 UTC, lleyton approved these changes

2024-02-12 04:34 UTC, merged